kind: Deployment
apiVersion: apps/v1


metadata:
  namespace: {{ .Values.nameSpace }}
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.serviceaccount.ingeress.controller }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - --api.insecure
            - --log.level=DEBUG
            - --accesslog
            - --entryPoints.web.Address=:8000
            - --entryPoints.websecure.Address=:4443
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080