apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-controller-role-binding
  namespace: {{.Values.nameSpace}}
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceaccount.ingeress.controller}}
roleRef:
    kind: ClusterRole
    name: traefik-ingress-controller-role
    apiGroup: rbac.authorization.k8s.io