apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-ingress-controller-developer-binding
  namespace: {{Values.nameSpace}}
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
roleRef:
    kind: Role
    name: developer
    apiGroup: rbac.authorization.k8s.io